# Generated by Django 2.2.7 on 2019-11-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkreditasiPt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_lemb', models.CharField(max_length=30)),
                ('npsn', models.CharField(max_length=6)),
                ('nm_akred', models.CharField(max_length=1)),
                ('sk_akred_sp', models.CharField(max_length=40)),
                ('tgl_sk_akred_sp', models.DateField()),
                ('tst_sk_akred_sp', models.DateField()),
                ('last_update', models.DateTimeField()),
                ('soft_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=15)),
                ('nm_sdm', models.CharField(max_length=30)),
                ('npsn', models.CharField(max_length=10)),
                ('kode_prodi', models.CharField(max_length=10)),
                ('tmt_sk_angkat', models.DateField()),
                ('nm_ikatan_kerja', models.CharField(max_length=20)),
                ('nm_stat_aktif', models.CharField(max_length=20)),
                ('nm_pangkat', models.CharField(max_length=20)),
                ('nm_jabfung', models.CharField(max_length=20)),
                ('pendidikan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_pd', models.CharField(max_length=200)),
                ('nipd', models.CharField(max_length=200)),
                ('tgl_masuk_sp', models.DateField()),
                ('tgl_keluar', models.DateField()),
                ('mulai_smt', models.CharField(max_length=10)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('tmpt_lahir', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField()),
                ('sks_smt', models.CharField(max_length=10)),
                ('ipk', models.CharField(max_length=10)),
                ('sks_total', models.CharField(max_length=10)),
                ('nm_lemb', models.CharField(max_length=200)),
                ('nm_prodi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pt', models.TextField(max_length=7)),
                ('nama_pt', models.CharField(max_length=120)),
                ('nm_bp', models.CharField(max_length=50)),
                ('stat_sp', models.CharField(max_length=6)),
                ('kode_prodi', models.TextField(max_length=10)),
                ('nm_prodi', models.CharField(max_length=200)),
                ('nm_jenj_didik', models.CharField(max_length=6)),
                ('nm_akred', models.CharField(max_length=20)),
                ('sk_akred_prodi', models.CharField(max_length=100)),
                ('tgl_sk_akred_prodi', models.DateField()),
                ('tst_sk_akred_prodi', models.DateField()),
                ('last_update', models.DateTimeField()),
                ('last_sync', models.DateTimeField()),
            ],
        ),
    ]
